"""What actually goes into the published artefacts.

``uv build`` builds from the working tree, and hatchling's default is to include
everything that is not gitignored -- which means untracked files too. Before this
was pinned down, the 0.2.0 sdist contained `.claude/settings.local.json` (local
cluster paths and session filenames) and
`examples/ukbb/10k_WB_5K_Irish/prepare_data_create_labels.sh`, a script whose own
header says "NOT for external users". Neither is tracked in git; both would have
been published.

A release cannot be withdrawn from an index in any meaningful sense, so this is
checked on the artefact rather than argued about in a comment. It is marked
``integration`` because it shells out to a real build.
"""

import shutil
import subprocess
import tarfile
import zipfile
from pathlib import Path

import pytest

pytestmark = pytest.mark.integration

REPO = Path(__file__).resolve().parents[2]

# Directories that exist in the repo and must never reach an index: local tool
# state, planning notes, and the example scripts that read controlled-access
# metadata. Examples are documentation, and they live in the repository.
FORBIDDEN_TOP_LEVEL = {".claude", ".superpowers", ".github", "examples", "assets", "docs"}

if shutil.which("uv") is None:
    pytest.skip("uv is needed to build the distributions", allow_module_level=True)


@pytest.fixture(scope="module")
def built(tmp_path_factory):
    out = tmp_path_factory.mktemp("dist")
    subprocess.run(
        ["uv", "build", "--out-dir", str(out)],
        cwd=REPO,
        check=True,
        capture_output=True,
    )
    return out


@pytest.fixture(scope="module")
def sdist_members(built):
    (sdist,) = built.glob("*.tar.gz")
    with tarfile.open(sdist) as archive:
        root = f"{sdist.name[: -len('.tar.gz')]}/"
        return sorted(
            name[len(root) :]
            for name in archive.getnames()
            if name.startswith(root) and name != root
        )


@pytest.fixture(scope="module")
def wheel_members(built):
    (wheel,) = built.glob("*.whl")
    with zipfile.ZipFile(wheel) as archive:
        return sorted(archive.namelist())


@pytest.fixture(scope="module")
def tracked():
    result = subprocess.run(
        ["git", "ls-files"], cwd=REPO, check=True, capture_output=True, text=True
    )
    return set(result.stdout.split())


class TestSdist:
    def test_it_ships_no_untracked_file(self, sdist_members, tracked):
        """The guard against a local build sweeping up working files.

        PKG-INFO is generated by the build and is the one expected exception.
        """
        files = [m for m in sdist_members if not m.endswith("/")]
        untracked = [m for m in files if m not in tracked and m != "PKG-INFO"]

        assert untracked == []

    def test_it_ships_none_of_the_forbidden_directories(self, sdist_members):
        present = {m.split("/")[0] for m in sdist_members} & FORBIDDEN_TOP_LEVEL

        assert present == set()

    def test_it_ships_the_package_and_its_tests(self, sdist_members):
        assert "src/manifold_genetics/__init__.py" in sdist_members
        assert "tests/unit/test_package_metadata.py" in sdist_members

    def test_it_ships_the_files_that_describe_the_release(self, sdist_members):
        assert {"README.md", "CHANGELOG.md", "LICENSE", "pyproject.toml"} <= set(sdist_members)


class TestWheel:
    def test_it_ships_the_type_marker(self, wheel_members):
        # PEP 561: without this, callers' type checkers ignore every annotation.
        assert "manifold_genetics/py.typed" in wheel_members

    def test_it_ships_only_the_package(self, wheel_members):
        top = {m.split("/")[0] for m in wheel_members}

        assert top == {"manifold_genetics", "manifold_genetics-0.2.0.dist-info"}

    def test_it_bundles_the_license(self, wheel_members):
        assert any(m.endswith("licenses/LICENSE") for m in wheel_members)
